### ISSUE TITLE
Build for RM-AC2100

### ISSUE THREAD

**Issue by kilroy98** [SWRT-dev/swrt-gpl#10]
Hello, when should we expect a new build for RM-AC2100? I saw you made some changes to work with bad blocks, and in my router there is a nand memory with 3 bad blocks and I would like to use your firmware. I can’t build the firmware myself, I don’t understand this :(

**Comment by paldier** [comment]
https://github.com/SWRT-dev/swrt-gpl/blob/master/README_en.md

**Comment by DevoUraq** [comment]
@kilroy98 

Have You Install The Firmware on 
Xiaomi Redmi AC2100

Really Want This Firmware

**Comment by kilroy98** [comment]
@DevoUraq no, sorry. My nand has three bad blocks and I can not install all the firmware.

**Comment by DevoUraq** [comment]
@kilroy98 

Thank You so Much For 
Your response Yes I can't install this firmware actually
I have tried That from luzetz Maybe i have Write his name correct and padavan but this firmware is just can't be installed 

Thanks Again Mate
