### ISSUE TITLE
Firmware and Breed

### ISSUE THREAD

**Issue by kilroy98** [SWRT-dev/swrt-gpl#14]
How can I flash this firmware using the Breed bootloader? Breed version - [r1416](https://blog.hackpascal.net/2022/07/2022-07-24-breed-update/)
Router - RMAC2100. For this router using Breed from R3G.

**Comment by kilroy98** [comment]
The question is still relevant

**Comment by paldier** [comment]
````
env set xiaomi.r3g.bootfw 2
env save
reset
````
Now, you can flash new firmware.
