### ISSUE TITLE
编译RM2100时报错

### ISSUE THREAD

**Issue by cainiao5** [SWRT-dev/swrt-gpl#19]
prebuild/private.o: In function `exec_uu':
(.text.exec_uu+0x0): multiple definition of `exec_uu'
ralink.o:ralink.c:(.text.exec_uu+0x0): first defined here
collect2: error: ld returned 1 exit status
make[4]: *** [Makefile:993：rc] 错误 1
make[4]: 离开目录“/home/cainiao5/swrt-gpl/release/src/router/rc”
make[3]: *** [Makefile:3434：rc] 错误 2
make[3]: 离开目录“/home/cainiao5/swrt-gpl/release/src/router”
make[2]: *** [Makefile:711：all] 错误 2
make[2]: 离开目录“/home/cainiao5/swrt-gpl/release/src-mtk-mips”
make[1]: *** [Makefile:5759：bin] 错误 2
make[1]: 离开目录“/home/cainiao5/swrt-gpl/release/src-mtk-mips”
make: *** [Makefile:5920：swrt-rm-ac2100] 错误 2

**Comment by paldier** [comment]
已更新

**Comment by cainiao5** [comment]
感谢大佬

**Comment by cainiao5** [comment]
make[3]: 离开目录“/home/cainiao5/swrt-gpl/release/src/router”
make[2]: *** [Makefile:711：all] 错误 2
make[2]: 离开目录“/home/cainiao5/swrt-gpl/release/src-mtk-mips”
make[1]: *** [Makefile:5759：bin] 错误 2
make[1]: 离开目录“/home/cainiao5/swrt-gpl/release/src-mtk-mips”
make: *** [Makefile:5920：swrt-rm-ac2100] 错误 2
cainiao5@cainiao5-PC:~/swrt-gpl/release/src-mtk-mips$


仍然报错
