### ISSUE TITLE
counting rx/tx packets on VIF/VAP with mt_wifi

### ISSUE THREAD

**Issue by i3roly** [SWRT-dev/swrt-gpl#20]
is this possible?

it seems the packets through virtual (slave) interfaces are not counted separately from their originating (master) interface.

**Comment by i3roly** [comment]
@paldier i closed ticket because it's not bug, but i wanted to know if you had answer to this question.;

**Comment by paldier** [comment]
mt_wifi don't have a phy interface, so don't support packet counting on vap.
