### ISSUE TITLE
Netgear R6800 刷B5.2.2成功後, 在系統設定中的登入名稱密碼皆無法修改

### ISSUE THREAD

**Issue by hikevin117** [SWRT-dev/swrt-gpl#21]
刷R6800_B5.2.2_50217-gbba1cd4, 之後的5.2.3也依然未修正. 在初始後設定完帳號密碼後, 在系統設定予修改帳號或密碼都只能如照片所示, 最多只能輸入一個字元.  是否有人有一樣問題?

![image](https://github.com/SWRT-dev/swrt-gpl/assets/78493380/5d828f5e-aea4-4e32-ac81-dd11aa17cb95)
![image](https://github.com/SWRT-dev/swrt-gpl/assets/78493380/b38da63c-1640-4c2d-a396-a89e6d683d8d)

**Comment by paldier** [comment]
可以自己编译新固件或者等下个版本发布
