### ISSUE TITLE
RT-ACRH17 5.2.3 无法访问部分界面

### ISSUE THREAD

**Issue by 4512369781** [SWRT-dev/swrt-gpl#22]
系统：Win10 21H2 x64
浏览器：Microsoft Edge 版本 116.0.1938.23 (正式版本) dev (64 位)
swrt 5.2.2 正常

更新5.2.3 后登录就如图所示：
![image](https://github.com/SWRT-dev/swrt-gpl/assets/30334394/e2ca0916-7a61-4c93-8555-3106c279701b)

点击 “无线路由器”后，再次出现登录界面，输入密码后暂时恢复正常，在日志里出现下面这些内容：
```
Jul 21 23:17:05 watchdog: restart httpd
Jul 21 23:17:05 rc_service: watchdog 699:notify_rc stop_httpd
Jul 21 23:17:06 kernel: _nvram_free: 699(watchdog) nvram_idx(0 / 1)
Jul 21 23:17:06 rc_service: watchdog 699:notify_rc start_httpd
Jul 21 23:17:06 RT-ACRH17: start httpd:80
Jul 21 23:17:06 httpd: Save SSL certificate...80
Jul 21 23:17:06 httpd: mssl_cert_key_match : PASS
Jul 21 23:17:06 httpd: Succeed to init SSL certificate...80
```
如果再次切换到“网络地图”，就又和第一张图一样了。

**Comment by paldier** [comment]
没发现问题

**Comment by 4512369781** [comment]
> 没发现问题

我找到原因了，触发操作如下：
1. 恢复出厂
2. 内部网络(LAN) -> DHCP 服务器 -> [启用手动指定功能 [是]] -> 添加一个**没有连接到路由器的设备** -> 应用本页面设置
3. 等待操作完成后，点击该条内容的图标，修改图标或着什么也不做，接着按下弹出窗口中的“应用本页面设置”后，就会出现无法访问部分页面的问题。

我在5.2.3之前的版本上修改过绑定条目的图标，所以才会在更新到5.2.3后出现这个错误。

**Comment by paldier** [comment]
可以自己编译新固件或者等下个版本发布

**Comment by paldier** [comment]
> 华硕 RT-ACRH17 固件 5.2.4 正式版发布后，该故障有一定缓解，但未能得到根除，并且在清除设置或重新刷入后仍会复现。   经测试，问题似乎变成当手动指定 DHCP 列表中存在_连接过_的设备，且该设备的自定义_名称_或_图标_被用户修改，故障就会发生。   问题表现为管理界面中的部分页面无响应，浏览器控制台抛出大量 `ERR_CONNECTION_REFUSED` 报错。   希望对排障有所帮助，仅供参考。

已修复
