### ISSUE TITLE
红米AX6000最新源码编译无法启动

### ISSUE THREAD

**Issue by zixiang5288** [SWRT-dev/swrt-gpl#24]
因5.2.3版会出现无法正常操作管理界面，右侧界面白板处显示拒绝接入
https://github.com/SWRT-dev/swrt-gpl/issues/22
提到用最新源码编译可解决，按照教程最新源码编译成功，升级和全新刷入都无法启动，求解，谢谢！

**Comment by paldier** [comment]
没发现问题
