### ISSUE TITLE
华硕 RT-ACRH17 固件 5.2.4 正式版 QoS 日志报错

### ISSUE THREAD

**Issue by Rounder-42** [SWRT-dev/swrt-gpl#25]
操作系统：Microsoft Windows 10 企业版 LTSC 2019 (x64)
浏览软件：Google Chrome 118.0.5993.106
固件版本：386_RTACRH17_B5.2.4-gcc66f8a
* * *
在流量管理面板中开启传统 QoS 功能，设置好上传和下载带宽（其它选项未改动），重启路由后会生成如下错误日志：
 
`Oct 28 00:00:43 qos: apply rules error(938)`
 
 
恢复原厂设置后，该故障也能复现。

**Comment by paldier** [comment]
已修复，可以自己编译或者等下个版本发布

**Comment by paldier** [comment]
没发现你说的问题
