### ISSUE TITLE
华硕 RT-ACRH17 新版 5.2.5 固件无法保存 DHCP 映射

### ISSUE THREAD

**Issue by Teo-Francis** [SWRT-dev/swrt-gpl#32]
## 本机配置
操作系统：Microsoft Windows 10 Enterprise LTSC 17763.5579
浏览软件：Google Chrome Stable 123.0.6312.91 (64-bit)
路由型号：ASUS RT-ACRH17
固件版本：4.0.0.4_RTACRH17_B5.2.5_50384-gda9baa4
 
## 故障现象
离线更新固件后，内网 DHCP 手动地址分配功能出错，条目变更无法储存。清空 NVRAM 后仍可复现。
 
![FEEDBACK](https://github.com/SWRT-dev/swrt-gpl/assets/165303126/2bcbb064-89f0-4d20-8b37-37883f65f335)
 
目前该问题较为影响使用，不知是否依然与 #22 和 #26 早先的修复措施有关。
 
希望调查有关缺陷并适时修正，非常感谢。

**Comment by 4512369781** [comment]
我更新到5.2.5后，发现已有的条目无法修改名称和图标，可能也是这个原因。

还有个问题是日志里的时间差了8个小时。

**Comment by paldier** [comment]
合并华硕最新代码造成的问题，目前华硕最新固件也是同样的问题

**Comment by paldier** [comment]
已经修复，可以自己编译或者等下个版本

**Comment by paldier** [comment]
> > 已经修复，可以自己编译或者等下个版本
> 
> 感谢 @paldier 修复故障，不过还有个困扰我多时的固件自行编译问题，想在此一并请教。
> 
> 无论是在推荐的 Ubuntu 18.04.6 LTS 还是 Linux Mint 19.1 Cinnamon Edition 系统中，搭建全新的虚拟机环境，并严格按照 README 逐项执行相关命令后，都会在中途收到如下报错：
> 
> ```
> ...
> ln -sf libeasy.so.3.0.0 libeasy.so.3
> ln -sf libeasy.so.3.0.0 libeasy.so
> make[6]: Leaving directory '/home/theo-francois/swrt-gpl/release/src/router/swrtmesh/libeasy/source'
> make[5]: Leaving directory '/home/theo-francois/swrt-gpl/release/src/router/swrtmesh/libeasy'
> make[5]: Entering directory '/home/theo-francois/swrt-gpl/release/src/router/swrtmesh/libeasy'
> mkdir -p /home/theo-francois/swrt-gpl/release/src-qca-ipq40xx/router/arm-musl/stage/usr/include/easy
> install -m 644 /home/theo-francois/swrt-gpl/release/src/router/swrtmesh/libeasy/source/{easy,event,utils,bufutil,cryptutil,ecc_cryptutil,if_utils,debug,hlist}.h /home/theo-francois/swrt-gpl/release/src-qca-ipq40xx/router/arm-musl/stage/usr/include/easy
> install: cannot stat '/home/theo-francois/swrt-gpl/release/src/router/swrtmesh/libeasy/source/{easy,event,utils,bufutil,cryptutil,ecc_cryptutil,if_utils,debug,hlist}.h': No such file or directory
> Makefile:22: recipe for target 'stage' failed
> make[5]: *** [stage] Error 1
> make[5]: Leaving directory '/home/theo-francois/swrt-gpl/release/src/router/swrtmesh/libeasy'
> Makefile:3: recipe for target 'all' failed
> make[4]: *** [all] Error 2
> make[4]: Leaving directory '/home/theo-francois/swrt-gpl/release/src/router/swrtmesh'
> Makefile:9990: recipe for target 'swrtmesh' failed
> make[3]: *** [swrtmesh] Error 2
> make[3]: Leaving directory '/home/theo-francois/swrt-gpl/release/src/router'
> Makefile:799: recipe for target 'all' failed
> make[2]: *** [all] Error 2
> make[2]: Leaving directory '/home/theo-francois/swrt-gpl/release/src-qca-ipq40xx'
> Makefile:6638: recipe for target 'bin' failed
> make[1]: *** [bin] Error 2
> make[1]: Leaving directory '/home/theo-francois/swrt-gpl/release/src-qca-ipq40xx'
> Makefile:6760: recipe for target 'rt-ac82u' failed
> make: *** [rt-ac82u] Error 2
> ```
> 
> 令人疑惑的是，错误信息中提及的文件均位于正确位置，该现象在更新 Toolchains 之后持续至今。
> 
> 若能指点迷津，本人不胜感激！

````
sudo ln -sf /bin/bash /bin/sh
````
应该是你用的版本是dash

**Comment by paldier** [comment]
修好了，看起来华硕新代码坑太多了
