### ISSUE TITLE
i don't think mt7621 supports CONFIG_WHNAT_SUPPORT

### ISSUE THREAD

**Issue by i3roly** [SWRT-dev/swrt-gpl#6]
yo @paldier,

i saw this commit 

35deeba5eca90bd411d6418cc7070f087f0ed932

i am not sure if MT7621 supports WHNAT because it requires "mediatek,wed" dts node.

if you look at openwrt's mtk_eth_soc.c driver in newer 5.x linux kernel, mediatek,wed node exists only for ARM-based devices (https://github.com/SUSE/kernel/blob/893e7de7ee89bdb6a4d59af80555a8704e23d65c/drivers/net/ethernet/mediatek/Kconfig)

are you *sure* WHNAT_SUPPORT works for MT7621?

i would like to see proper DTS configuratino for "mediatek,wed" nodes in MT7621.dtsi plus device dts.

right now this commit does not seem correct

edit: look in [drivers/net/wireless/mediatek/mt7615e/mt_wifi/embedded/plug_in/whnat/wed.c](
https://github.com/SWRT-dev/swrt-gpl/blob/master/release/linux/mtk/linux-5.4/drivers/net/wireless/mediatek/mt7615/5.1.0.0/mt_wifi/embedded/plug_in/whnat/wed.c):

it is looking for "mediatek,wed" node. i don't know how this would work...

**Comment by paldier** [comment]
`MODULE_SUPPORTED_DEVICE("mt7615 within mt7622");`
you are right

**Comment by i3roly** [comment]
just wanted to check with you @paldier that's all.

not about "being right". just making sure we are working together since i rely on your updates to the MTK source.

i am happy your answer provides clarification. 

will close ticket now.
