### ISSUE TITLE
Unable to make RT-AX53U firmware

### ISSUE THREAD

**Issue by 75Tushar** [SWRT-dev/swrt-gpl#7]
<pre><font color="#26A269"><b>axiom@axiom-pc</b></font>:<font color="#12488B"><b>~</b></font>$ cd mtk-toolchains
<font color="#26A269"><b>axiom@axiom-pc</b></font>:<font color="#12488B"><b>~/mtk-toolchains</b></font>$ sudo ln -sf $(pwd)/toolchain-mipsel_24kc_gcc-5.4.0_musl-1.1.24 /opt/
[sudo] password for axiom: 
<font color="#26A269"><b>axiom@axiom-pc</b></font>:<font color="#12488B"><b>~/mtk-toolchains</b></font>$ cd ../swrt-gpl/release/src-mtk-mips
<font color="#26A269"><b>axiom@axiom-pc</b></font>:<font color="#12488B"><b>~/swrt-gpl/release/src-mtk-mips</b></font>$ make rt-ax53u
/bin/sh: 1: cd: can&apos;t cd to /home/axiom/swrt-gpl/release/src-mtk-mips/../sdk
CONFIGURED MODEL: 
SPECIFIED  MODEL: RT-AX53U
DEFINED MODEL:    
----------------------------------------------------------------------------
!!! MODEL NAME MISMATCH.  REMOVE .config AND MAKE AGAIN. !!!
make: *** [Makefile:5833: rt-ax53u] Error 1
</pre>

any solution?

**Comment by paldier** [comment]
!!! MODEL NAME MISMATCH.  REMOVE .config AND MAKE AGAIN. !!!

**Comment by 75Tushar** [comment]
Output with `make rt-ax53u`
<pre><font color="#26A269"><b>axiom@axiom-pc</b></font>:<font color="#12488B"><b>~/swrt-gpl/release/src-mtk-mips</b></font>$ make rt-ax53u
/bin/sh: 1: cd: can&apos;t cd to /home/axiom/swrt-gpl/release/src-mtk-mips/../sdk
CONFIGURED MODEL: 
SPECIFIED  MODEL: RT-AX53U
DEFINED MODEL:    
----------------------------------------------------------------------------
!!! MODEL NAME MISMATCH.  REMOVE .config AND MAKE AGAIN. !!!
make: *** [Makefile:5833: rt-ax53u] Error 1
</pre>

After removing `.config`
<pre><font color="#26A269"><b>axiom@axiom-pc</b></font>:<font color="#12488B"><b>~/swrt-gpl/release/src-mtk-mips</b></font>$ make rt-ax53u
/bin/sh: 1: cd: can&apos;t cd to /home/axiom/swrt-gpl/release/src-mtk-mips/../sdk
/bin/sh: 1: export: 3LANPORT_DEVICE: bad variable name
make: *** [Makefile:5833: rt-ax53u] Error 2</pre>

Output with `make rtax53u`
<pre><font color="#26A269"><b>axiom@axiom-pc</b></font>:<font color="#12488B"><b>~/swrt-gpl/release/src-mtk-mips</b></font>$ make rtax53u
/bin/sh: 1: cd: can&apos;t cd to /home/axiom/swrt-gpl/release/src-mtk-mips/../sdk
</pre>

I have tried for others model too. It shows same error. Though I'm not an expert, Tried to edit Makefile Ln 116, Col 1
`export SDK_DIR := $(shell (cd $(shell pwd)/../sdk && pwd -P))` I was not successful.

**Comment by 75Tushar** [comment]
@paldier I saw your update. I tried again. Output is below

<pre><font color="#26A269"><b>axiom@axiom-pc</b></font>:<font color="#12488B"><b>~/swrt-gpl/release/src-mtk-mips</b></font>$ make rt-ax53u
warning: ignoring broken ref refs/tags/asuswrt_4.0.0.4.386rc4
warning: ignoring broken ref refs/tags/asuswrt_4.0.0.4.386rc4
fatal: ambiguous argument &apos;asuswrt_4.0.0.4.386rc4&apos;: unknown revision or path not in the working tree.
Use &apos;--&apos; to separate paths from revisions, like this:
&apos;git &lt;command&gt; [&lt;revision&gt;...] -- [&lt;file&gt;...]&apos;
fatal: cannot lock ref &apos;refs/tags/asuswrt_4.0.0.4.386rc4&apos;: unable to resolve reference &apos;refs/tags/asuswrt_4.0.0.4.386rc4&apos;: reference broken
fatal: cannot lock ref &apos;refs/tags/asuswrt_4.0.0.4.386rc4&apos;: unable to resolve reference &apos;refs/tags/asuswrt_4.0.0.4.386rc4&apos;: reference broken
fatal: cannot lock ref &apos;refs/tags/asuswrt_4.0.0.4.386rc4&apos;: unable to resolve reference &apos;refs/tags/asuswrt_4.0.0.4.386rc4&apos;: reference broken
fatal: cannot lock ref &apos;refs/tags/asuswrt_4.0.0.4.386rc4&apos;: unable to resolve reference &apos;refs/tags/asuswrt_4.0.0.4.386rc4&apos;: reference broken
fatal: cannot lock ref &apos;refs/tags/asuswrt_4.0.0.4.386rc4&apos;: unable to resolve reference &apos;refs/tags/asuswrt_4.0.0.4.386rc4&apos;: reference broken
fatal: cannot lock ref &apos;refs/tags/asuswrt_4.0.0.4.386rc4&apos;: unable to resolve reference &apos;refs/tags/asuswrt_4.0.0.4.386rc4&apos;: reference broken
fatal: cannot lock ref &apos;refs/tags/asuswrt_4.0.0.4.386rc4&apos;: unable to resolve reference &apos;refs/tags/asuswrt_4.0.0.4.386rc4&apos;: reference broken
CONFIGURED MODEL: 
SPECIFIED  MODEL: RT-AX53U
DEFINED MODEL:    
----------------------------------------------------------------------------
!!! MODEL NAME MISMATCH.  REMOVE .config AND MAKE AGAIN. !!!
make: *** [Makefile:5835: rt-ax53u] Error 1

<font color="#26A269"><b>axiom@axiom-pc</b></font>:<font color="#12488B"><b>~/swrt-gpl/release/src-mtk-mips</b></font>$ rm .config

<font color="#26A269"><b>axiom@axiom-pc</b></font>:<font color="#12488B"><b>~/swrt-gpl/release/src-mtk-mips</b></font>$ make rt-ax53u
warning: ignoring broken ref refs/tags/asuswrt_4.0.0.4.386rc4
warning: ignoring broken ref refs/tags/asuswrt_4.0.0.4.386rc4
fatal: ambiguous argument &apos;asuswrt_4.0.0.4.386rc4&apos;: unknown revision or path not in the working tree.
Use &apos;--&apos; to separate paths from revisions, like this:
&apos;git &lt;command&gt; [&lt;revision&gt;...] -- [&lt;file&gt;...]&apos;
fatal: cannot lock ref &apos;refs/tags/asuswrt_4.0.0.4.386rc4&apos;: unable to resolve reference &apos;refs/tags/asuswrt_4.0.0.4.386rc4&apos;: reference broken
fatal: cannot lock ref &apos;refs/tags/asuswrt_4.0.0.4.386rc4&apos;: unable to resolve reference &apos;refs/tags/asuswrt_4.0.0.4.386rc4&apos;: reference broken
fatal: cannot lock ref &apos;refs/tags/asuswrt_4.0.0.4.386rc4&apos;: unable to resolve reference &apos;refs/tags/asuswrt_4.0.0.4.386rc4&apos;: reference broken
fatal: cannot lock ref &apos;refs/tags/asuswrt_4.0.0.4.386rc4&apos;: unable to resolve reference &apos;refs/tags/asuswrt_4.0.0.4.386rc4&apos;: reference broken
fatal: cannot lock ref &apos;refs/tags/asuswrt_4.0.0.4.386rc4&apos;: unable to resolve reference &apos;refs/tags/asuswrt_4.0.0.4.386rc4&apos;: reference broken
fatal: cannot lock ref &apos;refs/tags/asuswrt_4.0.0.4.386rc4&apos;: unable to resolve reference &apos;refs/tags/asuswrt_4.0.0.4.386rc4&apos;: reference broken
fatal: cannot lock ref &apos;refs/tags/asuswrt_4.0.0.4.386rc4&apos;: unable to resolve reference &apos;refs/tags/asuswrt_4.0.0.4.386rc4&apos;: reference broken
/bin/sh: 1: export: 3LANPORT_DEVICE: bad variable name
make: *** [Makefile:5835: rt-ax53u] Error 2

<font color="#26A269"><b>axiom@axiom-pc</b></font>:<font color="#12488B"><b>~/swrt-gpl/release/src-mtk-mips</b></font>$ make rtax53u
warning: ignoring broken ref refs/tags/asuswrt_4.0.0.4.386rc4
warning: ignoring broken ref refs/tags/asuswrt_4.0.0.4.386rc4
fatal: ambiguous argument &apos;asuswrt_4.0.0.4.386rc4&apos;: unknown revision or path not in the working tree.
Use &apos;--&apos; to separate paths from revisions, like this:
&apos;git &lt;command&gt; [&lt;revision&gt;...] -- [&lt;file&gt;...]&apos;
fatal: cannot lock ref &apos;refs/tags/asuswrt_4.0.0.4.386rc4&apos;: unable to resolve reference &apos;refs/tags/asuswrt_4.0.0.4.386rc4&apos;: reference broken
fatal: cannot lock ref &apos;refs/tags/asuswrt_4.0.0.4.386rc4&apos;: unable to resolve reference &apos;refs/tags/asuswrt_4.0.0.4.386rc4&apos;: reference broken
fatal: cannot lock ref &apos;refs/tags/asuswrt_4.0.0.4.386rc4&apos;: unable to resolve reference &apos;refs/tags/asuswrt_4.0.0.4.386rc4&apos;: reference broken
fatal: cannot lock ref &apos;refs/tags/asuswrt_4.0.0.4.386rc4&apos;: unable to resolve reference &apos;refs/tags/asuswrt_4.0.0.4.386rc4&apos;: reference broken
fatal: cannot lock ref &apos;refs/tags/asuswrt_4.0.0.4.386rc4&apos;: unable to resolve reference &apos;refs/tags/asuswrt_4.0.0.4.386rc4&apos;: reference broken
fatal: cannot lock ref &apos;refs/tags/asuswrt_4.0.0.4.386rc4&apos;: unable to resolve reference &apos;refs/tags/asuswrt_4.0.0.4.386rc4&apos;: reference broken
fatal: cannot lock ref &apos;refs/tags/asuswrt_4.0.0.4.386rc4&apos;: unable to resolve reference &apos;refs/tags/asuswrt_4.0.0.4.386rc4&apos;: reference broken
</pre>

**Comment by paldier** [comment]
I have only tested on ubuntu/debian/mint, perhaps your os/git doesn't support `git tag  -fa`.
https://github.com/SWRT-dev/swrt-gpl/blob/cd1ba230af0e545ae1450860d8a4741e3226540b/release/src-rt/Makefile#L179

**Comment by 75Tushar** [comment]
I'm using ubuntu 22.04 LTS.
Which os version are you are using?

**Comment by 75Tushar** [comment]
I'm using Ubuntu 22.04 LTS.
Which OS version are you using?

**Comment by 75Tushar** [comment]
Please build a RT-AX53U firmware and update [swrt.site](https://www.swrt.site/Firmware_Download) database.
