### ISSUE TITLE
does mt_wifi support ms-chapv2+peap (client mode enterprise) authentication?

### ISSUE THREAD

**Issue by i3roly** [SWRT-dev/swrt-gpl#8]
^

someone asked me this and i thought it would, but maybe not.

i have rtdot1x program compiled, but it seems driver does not support MSCHAPv2?

**Comment by paldier** [comment]
https://github.com/SWRT-dev/swrt-gpl/blob/cd1ba230af0e545ae1450860d8a4741e3226540b/release/src/router/8021xd/common/ieee802_11_defs.h#L683

**Comment by i3roly** [comment]
thanks buddy i didn't know there was new rtdot1x

will see if i can figure out how to use this program.

only need this program to use WPA2-ENTERPRISE client mode right?

**Comment by paldier** [comment]
I'm not sure, maybe only WPA2?
https://github.com/SWRT-dev/swrt-gpl/blob/cd1ba230af0e545ae1450860d8a4741e3226540b/release/src/router/rc/sysdeps/ralink/ralink.c#L3969

**Comment by paldier** [comment]
https://github.com/SWRT-dev/swrt-gpl/blob/cd1ba230af0e545ae1450860d8a4741e3226540b/release/src/router/rc/sysdeps/ralink/ralink.c#L1770
only WPA2

**Comment by i3roly** [comment]
thanks

do you know anyone using it?

do you compile mt_wifi driver with PASSPOINT_R2 feature? to save space, i do not.

i have compiled new 8021xd program properly, it's much bigger than original even after using openssl :S 

big question is how to use it properly.

i have seen README but it does not provide much information for station mode.

i assume mt_wifi driver/radio will be in station mode to use MSCHAPv2 protocol, just not sure how to put in username password configuration into config file. i will mention your name in the other thread to show you what i mean.

**Comment by paldier** [comment]
i'm not sure, asuswrt does not support enterprise authentication in repeater mode, and we don‘t use it
maybe just add ApCliAuthMode ApCliEncrypType to config file

**Comment by i3roly** [comment]
will close.

btw @paldier do your linux-4.x builds with MT_WIFI 5.x have RX errors? mine have 5-10%. usually it's not noticeable but in driver 4.x this was never a problem.

i don't know why there are so many errors

**Comment by paldier** [comment]
not found

**Comment by i3roly** [comment]
You don't have lots of rx errors???

From: paldier
Sent: Wednesday, 2 November 2022 8:13 PM
To: SWRT-dev/swrt-gpl
Reply To: SWRT-dev/swrt-gpl
Cc: gagan sidhu; State change
Subject: Re: [SWRT-dev/swrt-gpl] does mt_wifi support ms-chapv2+peap (client mode enterprise) authentication? (Issue #8)


not found

**Comment by i3roly** [comment]
How can I pinpoint source of rx errors?

I want to know. You have none, right?

From: paldier
Sent: Wednesday, 2 November 2022 8:13 PM
To: SWRT-dev/swrt-gpl
Reply To: SWRT-dev/swrt-gpl
Cc: gagan sidhu; State change
Subject: Re: [SWRT-dev/swrt-gpl] does mt_wifi support ms-chapv2+peap (client mode enterprise) authentication? (Issue #8)


not found

**Comment by paldier** [comment]
where did you get rx error from

**Comment by i3roly** [comment]
I don't know man.

I know 5ghz has more rx errors than 2.4 ghz

I don't know the origin of the errors.

It's usually around 5 percent of total rx packets. I want to find out the origin of these errors.
From: paldier
Sent: Thursday, 3 November 2022 5:48 PM
To: SWRT-dev/swrt-gpl
Reply To: SWRT-dev/swrt-gpl
Cc: gagan sidhu; State change
Subject: Re: [SWRT-dev/swrt-gpl] does mt_wifi support ms-chapv2+peap (client mode enterprise) authentication? (Issue #8)


where did you get rx error from

**Comment by paldier** [comment]
I mean where did you see the rx error

**Comment by i3roly** [comment]
in ifconfig:

rai0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500  metric 1
        ether xxx txqueuelen 1000  (Ethernet)
        RX packets 366544  bytes 78440161 (74.8 MiB)
        RX errors 13389  dropped 1120  overruns 0  frame 0
        TX packets 681155  bytes 892927667 (851.5 MiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0
        device interrupt 26

**Comment by paldier** [comment]
```
ra0       Link encap:Ethernet  HWaddr 00:0C:43:26:46:E0  
          UP BROADCAST RUNNING ALLMULTI MULTICAST  MTU:1500  Metric:1
          RX packets:0 errors:42605 dropped:0 overruns:0 frame:0
          TX packets:0 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000 
          RX bytes:0 (0.0 B)  TX bytes:0 (0.0 B)
          Interrupt:31 

ra1       Link encap:Ethernet  HWaddr 00:0C:43:26:46:E1  
          UP BROADCAST RUNNING ALLMULTI MULTICAST  MTU:1500  Metric:1
          RX packets:887 errors:0 dropped:0 overruns:0 frame:0
          TX packets:261 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000 
          RX bytes:110162 (107.5 KiB)  TX bytes:71345 (69.6 KiB)

rai0      Link encap:Ethernet  HWaddr 00:0C:43:26:46:E2  
          UP BROADCAST RUNNING ALLMULTI MULTICAST  MTU:1500  Metric:1
          RX packets:748932 errors:0 dropped:0 overruns:0 frame:0
          TX packets:973268 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000 
          RX bytes:84230725 (80.3 MiB)  TX bytes:1193648734 (1.1 GiB)
```
yeah, it's a bug

**Comment by i3roly** [comment]
thanks for confirmation!

**Comment by i3roly** [comment]
@paldier 
do you have any success using STA mode on the RT_WIFI driver?

i am testing it now and i am not sure if am configuring it wrong.

this is my config file. for some reason it seems to still be acting in station mode?


```
Default
E2pAccessMode=2
CountryRegion=1
CountryRegionABand=0
CountryCode=CA
SSID=SSIDNAME
BssidNum=1
NetworkType=Infra
MACRepeaterOuiMode=2
WirelessMode=9
HideSSID=0
ShortSlot=1
PhyRateLimit=0
PreAntSwitch=0
AutoChannelSelect=3
IEEE80211H=1
own_ip_addr=0.0.0.0
WPAPSK=SOMEPASSWORD
DefaultKeyID=1
EncrypType=AES
AuthMode=WPA2PSK
RADIUS_Server=0.0.0.0
RADIUS_Port=1812
RADIUS_Key=ralink
IEEE8021X=0
EAPifname=br0
PreAuthifname=br0
WdsEnable=0
WdsEncrypType=NONE
WdsList=
WdsKey=
HT_BW=1
VHT_BW=0
HT_EXTCHA=1
OpMode=0
HT_OpMode=0
HT_MCS=33
TxRate=0
Channel=0
BasicRate=15
BeaconPeriod=100
DtimPeriod=1
TxPower=100
DisableOLBC=0
BGProtection=0
TXPreamble=0
RTSThreshold=2347
FragThreshold=2346
TxBurst=0
PktAggregate=0
TurboRate=0
WmmCapable=1
APAifsn=3;7;1;1
APCwmin=4;4;3;2
APCwmax=6;10;4;3
APTxop=0;0;94;47
APACM=0;0;0;0
BSSAifsn=3;7;2;2
BSSCwmin=4;4;3;2
BSSCwmax=10;10;4;3
BSSTxop=0;0;94;47
BSSACM=0;0;0;0
AckPolicy=0;0;0;0
NoForwarding=0
NoForwardingBTNBSSID=0
DfsEnable=1
DfsCalibration=1
PowerUpenable=1
ApCliEnable=0
CSPeriod=10
WirelessEvent=0
PreAuth=0
RekeyInterval=0
RekeyMethod=DISABLE
PMKCachePeriod=10
HSCounter=0
AccessPolicy0=0
AccessControlList0=
AccessPolicy1=0
AccessControlList1=
AccessPolicy2=0
AccessControlList2=
AccessPolicy3=0
AccessControlList3=
HT_HTC=1
HT_RDG=1
HT_MIMOPS=1
HT_LinkAdapt=0
HT_MpduDensity=5
HT_AutoBA=1
HT_AMSDU=1
HT_BAWinSize=64
HT_GI=0
HT_STBC=1
HT_BSSCoexistence=0
G_BAND_256QAM=0
VOW_Airtime_Fairness_En=0
VOW_RX_En=1
RED_Enable=1
UAPSDCapable=0
```

but now some clients are connecting to this radio instead of it acting in client mode.

i thought mt7615's mt_wifi has station mode built in, and i don't need to use CONFIG_MODE_STA? the sta files don't exist for it.

**Comment by paldier** [comment]
https://github.com/SWRT-dev/swrt-gpl/blob/6bee89df7130e40d6c1f64ad2cca700707080424/release/src/router/rc/sysdeps/ralink/ralink.c#L545
https://github.com/SWRT-dev/swrt-gpl/blob/6bee89df7130e40d6c1f64ad2cca700707080424/release/src/router/rc/sysdeps/ralink/ralink.c#L5280

**Comment by i3roly** [comment]
everythign in my RT2860.dat looks the same as yours.

but for some reason the interface doesn't connect to the other AP:

```
root@DD-WRT:~# iwconfig ra0
ra0       RTWIFI SoftAP  ESSID:"---to the fellas out there"  
          Mode:Master  Channel=5  Access Point: 78:98:E8:54:81:B0   
          Bit Rate=600 Mb/s   
          Link Quality=10/100  Signal level:0 dBm  Noise level:0 dBm
          Rx invalid nwid:0  Rx invalid crypt:0  Rx invalid frag:0
          Tx excessive retries:0  Invalid misc:0   Missed beacon:0

root@DD-WRT:~# ifconfig ra0
ra0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500  metric 1
        ether 78:98:e8:54:81:b0  txqueuelen 1000  (Ethernet)
        RX packets 0  bytes 0 (0.0 B)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 0  bytes 0 (0.0 B)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0
        device interrupt 25  

```

why?

am i doing something wrong? it doesn't even connect atall :(

**Comment by paldier** [comment]
why do you want ap to connect to another ap, ap is ap, not sta

**Comment by i3roly** [comment]
i want radio to connect to another ap, i thought this is 'sta' mode?

RT2860.dat file shown above is STA configuration (wirelessmode=9, OpMode=0, etc)

but iwconfig says it is in Master mode and not Station.

i want the radio to connect to another AP so i can use it as wan. trying to test client/station mode functionality.

my configuration file looks just like the one your firmware would generate. i don't know why the radio won't connect to the other AP.

i also tried:

iwpriv ra0 set SSID=name
iwpriv ra0 set Encryp

https://github.com/SWRT-dev/swrt-gpl/blob/530e1a739106a347890943c3125a7430e5dd259f/release/linux/mtk/linux-4.14/drivers/net/wireless/mediatek/mt7615/5.1.0.0/mt_wifi/embedded/doc/iwpriv_usage.txt#L360

```
	1. iwpriv ra0 set NetworkType=Infra
	2. iwpriv ra0 set AuthMode=WPA2PSK
	3. iwpriv ra0 set EncrypType=AES
	4. iwpriv ra0 set SSID=apname
	5. iwpriv ra0 set WPAPSK=key12345
	6. iwpriv ra0 set SSID=apname

```

but it doesn't work

**Comment by paldier** [comment]
ap is ap, not sta, you can't set ap as sta, this is an embedded device, ap works in ap mode, sta works in sta mode, all interface names and modes are in l1profile.dat, you can google for programming guide, of course it's chinglish,  just like me.

**Comment by i3roly** [comment]
I am following the guide.

Config file I showed you in earlier post is sta mode. Look at 'wirelessmode' and 'opmode' lines.

But radio won't go into sta mode properly. But iwconfig says radio is on master mode, not monitor mode. Don't know why

From: paldier
Sent: Saturday, 12 November 2022 11:10 PM
To: SWRT-dev/swrt-gpl
Reply To: SWRT-dev/swrt-gpl
Cc: gagan sidhu; State change
Subject: Re: [SWRT-dev/swrt-gpl] does mt_wifi support ms-chapv2+peap (client mode enterprise) authentication? (Issue #8)


ap is ap, not sta, you can't set ap as sta, this is an embedded device, ap works in ap mode, sta works in sta mode, all interface names and modes are in l1profile.dat, you can google for programming guide, of course it's chinglish, just like me.

**Comment by paldier** [comment]
when will you understand ap is ap, ap is not sta, forget everything that you think you know about pc, this is embedded device.

**Comment by i3roly** [comment]
But then how do you get sta mode if it's not from making config file with sta settings? Even your code makes this file

From: paldier
Sent: Sunday, 13 November 2022 6:08 AM
To: SWRT-dev/swrt-gpl
Reply To: SWRT-dev/swrt-gpl
Cc: gagan sidhu; State change
Subject: Re: [SWRT-dev/swrt-gpl] does mt_wifi support ms-chapv2+peap (client mode enterprise) authentication? (Issue #8)


when will you understand ap is ap, ap is not sta, forget everything that you think you know about pc, this is embedded device.

**Comment by i3roly** [comment]
it seems that DIR882 documentation says client mode on stock FW is possible:

![Screenshot 2022-11-13 at 6 50 48 AM](https://user-images.githubusercontent.com/36090395/201525308-7ebceb06-4361-4d99-a4be-5ac288db1003.png)

but latest stock fw for 2640 does not show anything like this.
![Screenshot 2022-11-13 at 6 52 50 AM](https://user-images.githubusercontent.com/36090395/201525355-7c3a8999-34b4-4bbd-b43e-ab50bea9b055.png)

maybe client mode is not ready on 5.x.x. driver yet

**Comment by i3roly** [comment]
@paldier i get what you're saying now.

repeater mode is better than station/client mode.

i always thought if repeater was supported, so was station/client, but this is not true here.

and when i think about it more: station mode does not allow the radio to act as an AP. this is why repeater mode is called "APSTA" because it connects to another AP (STA function) but then provide functionality to all clients (AP function).

cool

**Comment by paldier** [comment]
that's great.
router/ap mode: ap
repeater mode: sta + ap(bridge to lan, some firmwares call it wireless bridge mode)
wireless bridge mode: sta(bridge to lan, some firmwares call it repeater mode, and ap can be enabled)
wisp mode: sta(bridge to wan, some firmwares call it repeater mode, and ap can be enabled)

**Comment by i3roly** [comment]
is there a simple way to get names of hidden SSIDs?

right now i must find match on SSID name to act as repeater.
________________________________

**Comment by paldier** [comment]
you can't get names of hidden SSID, you can only set names of hidden SSID. hidden SSID means no SSID is sent in the frame. you can't get what doesn't exist.

**Comment by i3roly** [comment]
so you're saying if i have hidden ssid and want repeater mode, i need to try all ssids with no name until a match succeeds?




________________________________

**Comment by paldier** [comment]
if you don't know name of hidden ssid, you never can connect to it.

**Comment by i3roly** [comment]
and if i do?

then i need to try all hidden SSIDs returned from site survey, until authentication succeeds?




________________________________

**Comment by i3roly** [comment]
```
Nov 14 22:49:49 DD-WRT kern.emerg  kernel: [ 6401.820201] skbuff: skb_over_panic: text:804997a0 len:2786 put:1352 head:8cbe8900 data:8cbe8992 tail:0x8cbe9474 end:0x8cbe90c0 dev:<NULL>
Nov 14 22:49:49 DD-WRT kern.emerg  kernel: [ 6401.844795] bug on skb_panic:196
Nov 14 22:49:49 DD-WRT kern.emerg  kernel: [ 6401.851254] skbuff: skb_over_panic: text:804997a0 len:2662 put:1290 head:8cbe8080 data:8cbe8112 tail:0x8cbe8b78 end:0x8cbe8840 dev:<NULL>
Nov 14 22:49:49 DD-WRT kern.emerg  kernel: [ 6401.875835] bug on skb_panic:196
Nov 14 22:49:49 DD-WRT kern.emerg  kernel: [ 6401.882365] skbuff: skb_over_panic: text:804997a0 len:2834 put:1376 head:8cbf4d00 data:8cbf4d92 tail:0x8cbf58a4 end:0x8cbf54c0 dev:<NULL>
Nov 14 22:49:49 DD-WRT kern.emerg  kernel: [ 6401.906950] bug on skb_panic:196
Nov 14 22:49:49 DD-WRT kern.emerg  kernel: [ 6401.913435] skbuff: skb_over_panic: text:804997a0 len:2882 put:1400 head:8cbf3c00 data:8cbf3c92 tail:0x8cbf47d4 end:0x8cbf43c0 dev:<NULL>
Nov 14 22:49:49 DD-WRT kern.emerg  kernel: [ 6401.938015] bug on skb_panic:196
Nov 14 22:49:49 DD-WRT kern.emerg  kernel: [ 6401.944473] skbuff: skb_over_panic: text:804997a0 len:2890 put:1404 head:8cbf3380 data:8cbf3412 tail:0x8cbf3f5c end:0x8cbf3b40 dev:<NULL>

```
i assume you've seen this problem when using APSTA?

no crashes or BUG report, just this line.

**Comment by i3roly** [comment]
gonna try this (<= instead of >=)

https://github.com/SWRT-dev/swrt-gpl/blob/5dbb2f366fb101fbfebe27b8dbe2a93760069410/release/linux/mtk/linux-4.4.198/drivers/net/wireless/mediatek/mt7915/7.4.0.0/mt_wifi/include/os/rt_linux.h#L766

**Comment by i3roly** [comment]
```Feb 23 16:05:42 DD-WRT kern.warn  kernel: [   82.550456] AP inf up for ra_0(func_idx) OmacIdx=0
Feb 23 16:05:42 DD-WRT kern.warn  kernel: [   82.559830] AsicRadioOnOffCtrl(): DbdcIdx=0 RadioOn
Feb 23 16:05:42 DD-WRT kern.warn  kernel: [   82.559977] ApAutoChannelAtBootUp----------------->
Feb 23 16:05:42 DD-WRT kern.warn  kernel: [   82.559986] ApAutoChannelAtBootUp: AutoChannelBootup[0] = 0
Feb 23 16:05:42 DD-WRT kern.warn  kernel: [   82.559990] ApAutoChannelAtBootUp<-----------------
Feb 23 16:05:42 DD-WRT kern.warn  kernel: [   82.559995] ^[[41m ap_run_at_boot() : ACS is disable !!^[[m
Feb 23 16:05:42 DD-WRT kern.warn  kernel: [   82.560015] [PMF]APPMFInit:: apidx=0, MFPC=0, MFPR=0, SHA256=0
Feb 23 16:05:42 DD-WRT kern.warn  kernel: [   82.560097] wifi_sys_linkup(), wdev idx = 0
Feb 23 16:05:42 DD-WRT kern.warn  kernel: [   82.560112] wtc_acquire_groupkey_wcid: Found a non-occupied wtbl_idx:127 for WDEV_TYPE:1
Feb 23 16:05:42 DD-WRT kern.warn  kernel: [   82.560112]  LinkToOmacIdx = 0, LinkToWdevType = 1
Feb 23 16:05:43 DD-WRT kern.warn  kernel: [   82.697328] bssUpdateBmcMngRate (BSS_INFO_BROADCAST_INFO), CmdBssInfoBmcRate.u2BcTransmit= 8192, CmdBssInfoBmcRate.u2McTransmit = 8196
Feb 23 16:05:43 DD-WRT kern.warn  kernel: [   82.705606] UpdateBeaconHandler, BCN_UPDATE_INIT, OmacIdx = 0
Feb 23 16:05:43 DD-WRT kern.warn  kernel: [   82.705787] APStartUpForMbss: BssIndex = 0 channel = 100
Feb 23 16:05:43 DD-WRT kern.warn  kernel: [   82.705985] MtCmdTxPowerDropCtrl: ucPowerDrop: 100, BandIdx: 0
Feb 23 16:05:43 DD-WRT kern.warn  kernel: [   82.707829] MtCmdTxPwrShowInfo: ucTxPowerInfoCatg: 0, BandIdx: 0 
Feb 23 16:05:43 DD-WRT kern.warn  kernel: [   82.708004] [PMF]APPMFInit:: apidx=0, MFPC=0, MFPR=0, SHA256=0
Feb 23 16:05:43 DD-WRT kern.warn  kernel: [   82.708087] APStartUpForMbss: BssIndex = 0 channel = 100
Feb 23 16:05:43 DD-WRT kern.warn  kernel: [   82.708235] MtCmdTxPowerDropCtrl: ucPowerDrop: 100, BandIdx: 0
Feb 23 16:05:43 DD-WRT kern.warn  kernel: [   82.709755] MtCmdTxPwrShowInfo: ucTxPowerInfoCatg: 0, BandIdx: 0 
Feb 23 16:05:43 DD-WRT kern.warn  kernel: [   82.710035] ap_ftkd> Initialize FT KDP Module...
Feb 23 16:05:43 DD-WRT kern.warn  kernel: [   82.710050] Main bssid = 78:98:e8:54:81:b1
Feb 23 16:05:43 DD-WRT kern.warn  kernel: [   82.710127] (ApCliCtrlDisconnectReqAction) MLME Request disconnect.
Feb 23 16:05:43 DD-WRT kern.warn  kernel: [   82.710138] (ApCliCtrlDisconnectReqAction) 2. Before do ApCliLinkDown. ifIndex = 0, bValid = 0
Feb 23 16:05:44 DD-WRT kern.warn  kernel: [   83.721756] ApCliValidateRSNIE(): Candidate Security AKMMap=WPA2PSK, PairwiseCipher=AES, GroupCipher=AES
Feb 23 16:05:44 DD-WRT kern.warn  kernel: [   83.721791] ApCliCheckHt :  channel=100,  my extcha=0, root ap extcha=1, inconsistent!!
Feb 23 16:05:44 DD-WRT kern.warn  kernel: [   83.722187] ApCliValidateRSNIE(): Candidate Security AKMMap=WPA2PSK, PairwiseCipher=AES, GroupCipher=AES
Feb 23 16:05:44 DD-WRT kern.warn  kernel: [   83.722202] ApCliCheckHt :  channel=100,  my extcha=0, root ap extcha=1, inconsistent!!
Feb 23 16:05:45 DD-WRT kern.warn  kernel: [   84.870184] ERROR: BSS idx (0) nor ready. (subtype 11)
Feb 23 16:05:45 DD-WRT kern.warn  kernel: [   84.891175] ApCliCheckHt :  channel=100,  my extcha=0, root ap extcha=1, inconsistent!!
Feb 23 16:05:45 DD-WRT kern.warn  kernel: [   84.891209] (ApCliLinkUp) ifIndex = 0!!!
Feb 23 16:05:45 DD-WRT kern.warn  kernel: [   84.891291] [DfsCacNormalStart] Normal start. Enable MAC TX
Feb 23 16:05:45 DD-WRT kern.warn  kernel: [   84.905787] [WrapDfsRadarDetectStart]: DfsChBand[0]: 0, DfsChBand[1]: 0
Feb 23 16:05:45 DD-WRT kern.warn  kernel: [   84.905822] wifi_sys_linkup(), wdev idx = 5
Feb 23 16:05:45 DD-WRT kern.warn  kernel: [   84.905837] wtc_acquire_groupkey_wcid: Found a non-occupied wtbl_idx:126 for WDEV_TYPE:128
Feb 23 16:05:45 DD-WRT kern.warn  kernel: [   84.905837]  LinkToOmacIdx = 1, LinkToWdevType = 128
Feb 23 16:05:45 DD-WRT kern.warn  kernel: [   84.905909] bssUpdateBmcMngRate (BSS_INFO_BROADCAST_INFO), CmdBssInfoBmcRate.u2BcTransmit= 8192, CmdBssInfoBmcRate.u2McTransmit = 8196
Feb 23 16:05:45 DD-WRT kern.info  kernel: [   84.915128] IPv6: ADDRCONF(NETDEV_CHANGE): apclii0: link becomes ready
Feb 23 16:05:45 DD-WRT kern.warn  kernel: [   84.998157] oooWPAParseEapolKeyData : the Group install  (1)
Feb 23 16:05:45 DD-WRT kern.warn  kernel: [   84.998176] PeerPairMsg3Action(1): update CCMP_BC_PN to 0
Feb 23 16:05:45 DD-WRT user.info  ap_clienti: apclii0 is associated
Feb 23 16:06:07 DD-WRT authpriv.info  dropbear[1281]: Child connection from 192.168.2.101:49976
Feb 23 16:06:10 DD-WRT kern.alert  kernel: [  109.749143] fast-classifier: shutting down
Feb 23 16:06:10 DD-WRT user.info  service: [sfe] : shortcut forwarding engine successfully stopped
Feb 23 16:06:10 DD-WRT kern.alert  kernel: [  109.941570] fast-classifier (PBR safe v2.1.6b): starting up
Feb 23 16:06:10 DD-WRT kern.alert  kernel: [  109.952910] fast-classifier: registered
Feb 23 16:06:10 DD-WRT user.info  service: [sfe] : shortcut forwarding engine successfully started
Feb 23 16:06:11 DD-WRT user.info  service: [wan] : WAN is up. IP: 192.168.1.6
Feb 23 16:06:11 DD-WRT user.info  service: [dnsmasq] : daemon successfully stopped
Feb 23 16:06:11 DD-WRT user.info  service: [dnsmasq] : successfully started
Feb 23 16:06:11 DD-WRT kern.alert  kernel: [  111.059553] fast-classifier: shutting down
Feb 23 16:06:11 DD-WRT user.info  service: [sfe] : shortcut forwarding engine successfully stopped
Feb 23 16:06:11 DD-WRT authpriv.notice  dropbear[1281]: Password auth succeeded for 'root' from 192.168.2.101:49976
Feb 23 16:06:12 DD-WRT user.info  service: [vpn modules] : vpn modules successfully unloaded
Feb 23 16:06:12 DD-WRT user.info  service: [vpn modules] : nf_conntrack_proto_gre successfully loaded
Feb 23 16:06:12 DD-WRT user.info  service: [vpn modules] : nf_nat_proto_gre successfully loaded
Feb 23 16:06:12 DD-WRT user.info  service: [vpn modules] : nf_conntrack_pptp successfully loaded
Feb 23 16:06:12 DD-WRT user.info  service: [vpn modules] : nf_nat_pptp successfully loaded
Feb 23 16:06:12 DD-WRT kern.alert  kernel: [  112.502827] fast-classifier (PBR safe v2.1.6b): starting up
Feb 23 16:06:12 DD-WRT kern.alert  kernel: [  112.514321] fast-classifier: registered
Feb 23 16:06:12 DD-WRT user.info  service: [sfe] : shortcut forwarding engine successfully started
Feb 23 16:06:13 DD-WRT user.info  service: [sfe] : shortcut forwarding engine successfully started
Feb 23 16:06:13 DD-WRT user.info  service: [process_monitor] : successfully started
Feb 23 16:06:14 DD-WRT kern.info  kernel: [  113.820523] br0Ip = c0a80201
Feb 23 16:06:14 DD-WRT kern.info  kernel: [  113.820538] brNetmask = ffffff00
Feb 23 16:06:14 DD-WRT daemon.debug  ntpclient[1549]: Connecting to 2.pool.ntp.org [37.59.63.125] ...
Nov 16 02:59:30 DD-WRT daemon.info  ntpclient[1549]: Time set from 2.pool.ntp.org [37.59.63.125].
Nov 16 02:59:30 DD-WRT daemon.info  process_monitor[1548]: Cyclic NTP Update success (servers 2.pool.ntp.org 212.18.3.19 88.99.174.22)
Nov 16 02:59:30 DD-WRT daemon.info  process_monitor[1548]: Local timer delta is 1663930397
Nov 16 02:59:30 DD-WRT kern.alert  kernel: [  114.374838] fast-classifier: shutting down
Nov 16 02:59:30 DD-WRT user.info  service: [sfe] : shortcut forwarding engine successfully stopped
Nov 16 02:59:30 DD-WRT kern.alert  kernel: [  114.583903] fast-classifier (PBR safe v2.1.6b): starting up
Nov 16 02:59:30 DD-WRT kern.alert  kernel: [  114.595312] fast-classifier: registered
Nov 16 02:59:30 DD-WRT user.info  service: [sfe] : shortcut forwarding engine successfully started
Nov 16 02:59:31 DD-WRT kern.alert  kernel: [  115.395711] fast-classifier: shutting down
Nov 16 02:59:31 DD-WRT user.info  service: [sfe] : shortcut forwarding engine successfully stopped
Nov 16 02:59:32 DD-WRT user.info  service: [vpn modules] : vpn modules successfully unloaded
Nov 16 02:59:32 DD-WRT user.info  service: [vpn modules] : nf_conntrack_proto_gre successfully loaded
Nov 16 02:59:32 DD-WRT user.info  service: [vpn modules] : nf_nat_proto_gre successfully loaded
Nov 16 02:59:32 DD-WRT user.info  service: [vpn modules] : nf_conntrack_pptp successfully loaded
Nov 16 02:59:32 DD-WRT user.info  service: [vpn modules] : nf_nat_pptp successfully loaded
Nov 16 02:59:33 DD-WRT kern.alert  kernel: [  116.821856] fast-classifier (PBR safe v2.1.6b): starting up
Nov 16 02:59:33 DD-WRT kern.alert  kernel: [  116.833264] fast-classifier: registered
Nov 16 02:59:33 DD-WRT user.info  service: [sfe] : shortcut forwarding engine successfully started
Nov 16 02:59:34 DD-WRT user.info  service: [sfe] : shortcut forwarding engine successfully started
Nov 16 02:59:34 DD-WRT daemon.debug  process_monitor[1548]: Restarting cron (time sync change)
Nov 16 02:59:34 DD-WRT user.info  service: [cron] : daemon successfully stopped
Nov 16 02:59:34 DD-WRT user.info  service: [cron] : successfully started
Nov 16 02:59:34 DD-WRT cron.info  cron[1824]: (CRON) STARTUP (fork ok)
Nov 16 02:59:34 DD-WRT daemon.info  process_monitor[1548]: [process_monitor] : cleanup timers
Nov 16 02:59:34 DD-WRT user.info  service: [process_monitor] : daemon successfully stopped
Nov 16 02:59:34 DD-WRT user.info  service: [process_monitor] : successfully started
Nov 16 02:59:34 DD-WRT daemon.debug  process_monitor[1828]: We need to re-update after 3600 seconds
Nov 16 02:59:34 DD-WRT daemon.info  process_monitor[1828]: [process_monitor] : set timer: 3600 seconds, callback: ntp_main()

```

[![BONGIOVANNI](https://img.youtube.com/vi/SRvCvsRp5ho/0.jpg)](https://www.youtube.com/watch?v=SRvCvsRp5ho)

@paldier

**Comment by i3roly** [comment]
stay safe @paldier @hanwckf @yonsm @immortalwrt

wishing you guys all the best from across the pacific!




________________________________
